apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - image: mongo:latest
        name: mongo
        ports:
        - containerPort: 27017
          name: mongo
        args:
          - "--tlsMode"
          - "requireTLS"
          - "--tlsCertificateKeyFile"
          - "/etc/mongodb/mongodb.pem"
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
        - name: cert-volume
          mountPath: "/etc/mongodb"
          readOnly: true
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc
      - name: cert-volume
        secret:
          secretName: mongodb-certs
		  