apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:latest
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "4fAXg!jq@2&8B986hAU@J#T"
        ports:
        - containerPort: 3306
          name: mysql
        args:
          - "--ssl-ca=/etc/mysql/ca.pem"
          - "--ssl-cert=/etc/mysql/server-cert.pem"
          - "--ssl-key=/etc/mysql/server-key.pem"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        - name: cert-volume
          mountPath: "/etc/mysql"
          readOnly: true
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: cert-volume
        secret:
          secretName: mysql-certs
