apiVersion: autoscaling/v2
kind: VerticalPodAutoscaler
metadata:
  name: vpa-mysql
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mysql
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
      - containerName: mysql
        minAllowed:
          cpu: "250m"
          memory: "1Gi"
        maxAllowed:
          cpu: "7000m"
          memory: "28Gi"
