version: '3.8'
services:

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/deinedatenbank
      SPRING_DATASOURCE_USERNAME: deinUsername
      SPRING_DATASOURCE_PASSWORD: deinPasswort
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: deinedatenbank
      POSTGRES_USER: deinUsername
      POSTGRES_PASSWORD: deinPasswort
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
