apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - image: mongo:latest
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "500m"
        name: mongo
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        - name: cert-volume
          mountPath: /mongo-certs
          readOnly: true
        command:
        - mongod
        - --tlsMode=requireTLS
        - --tlsCertificateKeyFile=/mongo-certs/server-key.pem
        - --tlsCAFile=/mongo-certs/ca.pem
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: PASSWORD_GOES_HERE
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: pvc-mongodb
      - name: cert-volume
        secret:
          secretName: mongo-certs